---
- name: CoreDNS 安装
  when: skip_coredns | bool
  block:
    - name: 创建 kube-coredns 组件配置文件目录
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0644
      with_items:
        - "{{ addons_dir }}/coredns"

    - name: 渲染 coredns 配置文件
      ansible.builtin.template:
        src: "{{ item.src }}.j2"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { src: "coredns/coredns.yaml", dest: "{{ addons_dir }}/coredns/coredns.yaml" }
        - { src: "coredns/autoscale.yaml", dest: "{{ addons_dir }}/coredns/autoscale.yaml" }
        - { src: "coredns/nodelocaldns.yaml", dest: "{{ addons_dir }}/coredns/nodelocaldns.yaml" }
